[package]
name = "lulu-git"
maintainers = ["alyrow"]
description = "Concept of package manager built on top of apt for handling git repositories"
url = "localhost"
source = "https://github.com/alyrow/lulu.git"
arch = ["any"]
license = []
provides = ["lulu"]
postinst = '''
#!/bin/sh
set -e

lulu setup

'''

[dependencies.runtime]
fakeroot = { is = "APT" }
"libapt-pkg6.0" = { is = "APT" }

[dependencies.build]
libapt-pkg-dev = { is = "APT" }
gcc = { is = "APT" }
pkg-config = { is = "APT" }
libssl-dev = { is = "APT" }
"g++" = { is = "APT" }

[dependencies.optional]

[script]
prepare = '''
'''
build = '''
export PATH=$PATH:$HOME/.cargo/bin/
cargo update
cargo build --release
'''
check = '''

'''
package = '''
mkdir -p $pkgdir/usr/bin
mkdir -p $pkgdir/etc
install -Dm755 target/release/lulu $pkgdir/usr/bin/lulu
install -Dm644 lulu.conf $pkgdir/etc/lulu.conf
'''
